# Generated by Django 4.1.2 on 2022-10-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={"verbose_name": "Подписчик", "verbose_name_plural": "Подписчики"},
        ),
    ]
