# Generated by Django 4.1.2 on 2022-10-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimg",
            name="image",
            field=models.ImageField(
                upload_to="product_images/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="изображение",
            ),
        ),
    ]
