# Generated by Django 4.1.2 on 2022-10-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productimg_image_alter_productimg_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активен"),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активен"),
        ),
    ]
