# Generated by Django 4.1.2 on 2022-10-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_price_alter_product_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_decription",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="короткое описание"
            ),
        ),
    ]
