# Generated by Django 4.1.2 on 2022-10-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_short_decription"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimg",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="главная картинка"),
        ),
    ]
