# Generated by Django 4.1.2 on 2022-10-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_adress",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="адрес",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productorder", name="nmb", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="productorder",
            name="price_per_item",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productorder",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
