# Generated by Django 4.1.2 on 2022-10-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_price_alter_product_is_active_and_more"),
        ("orders", "0003_rename_total_amount_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.status",
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Общая стоимость",
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активен"),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="nmb",
            field=models.IntegerField(default=1, verbose_name="количество"),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="order",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
                verbose_name="заказ",
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="price_per_item",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="цена товара"
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="стоимость"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активен"),
        ),
    ]
