# Generated by Django 4.1.2 on 2022-10-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_status_alter_order_total_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productorder",
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказе",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создан"),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлен"),
        ),
        migrations.AlterField(
            model_name="status",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создан"),
        ),
        migrations.AlterField(
            model_name="status",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлен"),
        ),
    ]
