# Generated by Django 4.1.2 on 2022-10-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_productinbasket"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinbasket",
            name="session_key",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
